services:
  db:
    image: postgres:16-bullseye
    # restart: always
    ports:
      - '${DB_PORT}:${DB_PORT}'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: cncinvent
    volumes:
      - ./postgres:/var/lib/postgresql/data

  # pgAdmin:
  #   image: dpage/pgadmin4:7
  #   # restart: always
  #   ports:
  #     - 8090:80
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@gmail.com
  #     PGADMIN_DEFAULT_PASSWORD: 1234
  #   container_name: PGAdmin42
